stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    - data/raw/iris.csv
    outs:
    - data/processed/X_train.csv
    - data/processed/X_test.csv
    - data/processed/y_train.csv
    - data/processed/y_test.csv
    params:
    - params.yaml:
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/processed/X_train.csv
    - data/processed/X_test.csv
    - data/processed/y_train.csv
    - data/processed/y_test.csv
    outs:
    - model.pkl
    params:
    - params.yaml:
